import "@/app/(login)/globals.css";
import Sidebar from "./components/navbar/Sidebar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex h-screen">
        <Sidebar />
        <main className="w-5/6">
        {children}</main>
      </body>
    </html>
  );
}
